### ISSUE TITLE
Window is too tall for standard monitors

### ISSUE THREAD

**Issue by AveryLychee** [SolviQorda/lambdalumps#12]
The window for the game is 1300px tall, which is taller than my largest monitor (1080px vertically, which is fairly standard for monitors)

**Comment by SolviQorda** [comment]
Going to try and fix this now!

**Comment by SolviQorda** [comment]
Have attempted this with branch 'adjusting-screen-size-for-standard-resolution" - is that better?

**Comment by AveryLychee** [comment]
That's much better – it fits nicely in my screen, which means I can see all of the important information (unlike before, where I couldn't see the next piece info and the bottom of the play area at the same time)
